server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false # 开发环境设置为false，生产环境应设置为true

spring:
  profiles:
    active: dev # 默认使用开发环境配置
  application:
    name: Kuri
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kuri?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  # 数据初始化
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
  # 时间格式化配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  # 缓存配置
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s
  # AI服务配置
  ai:
    dashscope:
      api-key: sk-402663c949e84e688ca03f6a627f5aed
    alibaba:
      mcp:
        nacos:
          namespace: 4ad3108b-4d44-43d0-9634-3c1ac4850c8c
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          client:
            enabled: true
            sse:
              connections:
                server1:
                  service-name: webflux-mcp-server
                  version: 1.0.0
    mcp:
      client:
        enabled: true
        name: mcp-client-webflux
        version: 0.0.1
        initialized: true
        request-timeout: 600s
        nacos-enabled: true
        type: sync
        toolcallback:
          enabled: true
        root-change-notification: true

# 日志配置
logging:
  level:
    root: INFO
    com.kuri: DEBUG
    org.springframework: INFO
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/kuri.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.kuri.backend.*.model,com.kuri.backend.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# PageHelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# JWT配置
jwt:
  secret: your-secret-key-here-should-be-very-long-and-secure
  expiration: 86400000 # 24小时
  header: Authorization
  tokenPrefix: Bearer

# 应用自定义配置
kuri:
  upload:
    path: uploads/
    allowed-types: jpg,jpeg,png,gif
    max-size: 10485760 # 10MB 