server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        secure: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kuri_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  cache:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=60s

logging:
  level:
    root: INFO
    com.kuri: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 