server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        secure: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  tomcat:
    max-threads: 200
    max-connections: 10000
    accept-count: 100
  # SSL配置 - 生产环境启用HTTPS
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:kuri_prod}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  # 数据初始化
  sql:
    init:
      mode: never # 生产环境不自动初始化数据库
  # 缓存配置
  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1800s

# 日志配置
logging:
  level:
    root: WARN
    com.kuri: INFO
  file:
    name: /var/log/kuri/application.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 监控配置 - 生产环境限制访问
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: never
  server:
    port: 8081 # 单独的管理端口

# JWT配置
jwt:
  expiration: 43200000 # 12小时 